version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks: 
      - default
  nginx:
    build:
        dockerfile: ./nginx.dockerfile
        context: .
    image: nginx
    container_name: container-lb
    ports:
        - "8080:8080"
    depends_on:
        - "server-1"
        - "server-2"
        - "server-3"
    networks: 
      - default
  server-1:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/baseline
    depends_on:
      - db
    ports:
    - '8081:8080'
    networks: 
      - default
  server-2:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/baseline
    depends_on:
      - db
    ports:
      - '8082:8080'
    networks: 
      - default
  server-3:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/baseline
    depends_on:
      - db
    ports:
    - '8083:8080'
    networks: 
      - default
volumes:
  db:
    driver: local

networks: 
    default:
        driver: bridge