version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks: 
      - default
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  nginx:
    build:
        dockerfile: ./nginx.dockerfile
        context: .
    image: nginx
    restart: always
    ports:
        - "8080:8080"
    depends_on:
        - "server-1"
        - "server-2"
        - "server-3"
    networks: 
      - default
  server-1:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/improved
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/  
    depends_on:
      - db
      - rabbitmq
    ports:
    - '8081:8080'
    networks: 
      - default
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  server-2:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/improved
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq
    ports:
      - '8082:8080'
    networks: 
      - default
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  server-3:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/improved
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq
    ports:
      - '8083:8080'
    networks: 
      - default
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  consumer:
    build:
      context: consumer
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/improved
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq
    networks: 
      - default
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
volumes:
  db:
    driver: local
  rabbitmq_data:
  rabbitmq_log:  

networks: 
    default:
        driver: bridge